config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    unauthenticated do
      root "main#index"
    end

    authenticated :user do
      root "maps#index", as: :authenticated_root
    end

    resources :maps, except: [:edit] do
      resources :layers, only: [:new]
      resources :access_groups, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :layers, except: [:index, :new, :edit] do
      member do
        get :schema
        get :geojson
      end
      resources :rows, only: [:new, :create, :update, :destroy]
    end
    resources :fields, only: [:create, :update, :destroy]

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/:locale" => "main#index"
    get "share/:token", to: "access_groups#enter_by_link", as: "share_link"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/access_group.rb
# == Schema Information
#
# Table name: access_groups
#
#  id         :uuid             not null, primary key
#  name       :text
#  role_type  :enum             not null
#  token      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  map_id     :uuid             not null
#
# Indexes
#
#  index_access_groups_on_map_id  (map_id)
#
# Foreign Keys
#
#  fk_rails_...  (map_id => maps.id)
#
class AccessGroup < ApplicationRecord
  # Attributes
  enum :role_type, {owner: "owner", editor: "editor", contributor: "contributor", viewer: "viewer"}

  # Relationships
  has_and_belongs_to_many :users
  belongs_to :map

  accepts_nested_attributes_for :users

  # Validations
  validates :role_type, presence: true

  # Hooks
  before_destroy :map_must_have_an_owner

  def map_must_have_an_owner
    return if destroyed_by_association&.inverse_of&.name == :map
    return if map.access_groups.owner.where.not(id: self).exists?

    errors.add(:map, :must_have_an_owner)
    throw(:abort)
  end

  def build_dom_id
    if persisted?
      dom_id(self)
    elsif token.present?
      "new_access_group_by_token"
    else
      "new_access_group_by_email"
    end
  end
end

app/controllers/access_groups_controller.rb
class AccessGroupsController < ApplicationController
  before_action :set_access_group, only: %i[update destroy]

  def index
    @map = current_user.maps.find(params["map_id"])

    authorize @map.access_groups.new
    @access_groups = policy_scope(@map.access_groups).includes(:users)
  end

  def create
    @map = current_user.maps.find(params["map_id"])
    @access_group = authorize @map.access_groups.new(create_access_group_params)

    if @access_group.save
      @access_group.users.each do |user|
        if user.invitation_sent_at.blank?
          user.invite!
        end
      end
      redirect_to map_access_groups_path(@map), notice: t("helpers.message.access_group.created")
    else
      redirect_to map_access_groups_path(@map), alert: t("common.failed", msg: @access_group.errors.full_messages.to_sentence)
    end
  end

  # Someone access the page through a link
  # If the user is signed in we add them to the users list of that access group
  # Other wise, we create a user without email
  def enter_by_link
    skip_authorization
    access_group = AccessGroup.find_by(token: params[:token])
    if user_signed_in?
      access_group.users << current_user unless access_group.users.exists?(current_user.id)
    else
      user = access_group.users.create(email: nil, remember_me: false)
      sign_in user
    end
    redirect_to access_group.map
  end

  def update
    @map = @access_group.map
    if @access_group.update(update_access_group_params)
      redirect_to map_access_groups_path(@map), notice: t("helpers.message.access_group.updated")
    else
      redirect_to map_access_groups_path(@map), alert: t("common.failed", msg: @access_group.errors.full_messages.to_sentence)
    end
  end

  def destroy
    @map = @access_group.map
    if @access_group.destroy
      redirect_to map_access_groups_path(@map), alert: t("helpers.message.access_group.destroyed")
    else
      redirect_to map_access_groups_path(@map), alert: t("common.failed", msg: @access_group.errors.full_messages.to_sentence)
    end
  end

  private

  def set_access_group
    @access_group = authorize AccessGroup.find(params[:id])
  end

  def create_access_group_params
    create_params = params.require(:access_group).permit(:role_type, :token, :name, users_attributes: [:email])
    if (existing_user = User.find_by(email: create_params.dig(:users_attributes, "0", :email)))
      create_params.delete(:users_attributes)
      create_params[:users] = [existing_user]
    end

    create_params
  end

  def update_access_group_params
    params.require(:access_group).permit(:role_type, :name)
  end
end

app/views/access_groups/_access_group.html.erb
<% delete_message = access_group.users.include?(current_user) ? t(".delete_self") : t("common.confirm") %>
<div class="main-element" id="<%= access_group.build_dom_id %>">
  <%= form_with(model: access_group.new_record? ? [access_group.map, access_group] : access_group) do |form| %>
    <% if access_group.token.present? %>
      <%= form.hidden_field :token unless access_group.persisted? %>
      <% if access_group.persisted? %>
        <div class="form__field" data-controller="clipboard">
          <%= form.label :url_to_share, t(".url_to_share") %>
          <div class="input-with-button">
            <%= text_field_tag :url_to_share, share_link_url(access_group.token), data: {clipboard_target: "source"}, autocomplete: :off %>
            <button data-action="clipboard#copy"><%= embedded_svg "copy.svg" %></button>
          </div>
        </div>
      <% end %>
      <div class="form__field">
        <%= form.label :name, t(".url_name") %><br>
        <%= form.text_field :name %>
      </div>
    <% else %>
      <%= form.fields_for :users do |f| %>
        <div class="form__field">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
      <% end %>
    <% end %>

    <div class="form__field">
      <%= form.label :role_type, t(".type") %>
      <%= form.select :role_type, options_for_select(AccessGroup.role_types.map { |access_group| [AccessGroup.human_attribute_name(access_group[0]), access_group[1]] }, access_group.role_type) %>
    </div>

    <% if access_group.persisted? %>
      <%= form.submit t("helpers.link.access_group.modify"), class: "form__button form__button--confirm" %>
      <%= link_to t("helpers.link.access_group.delete"), access_group, data: {turbo_method: :delete, turbo_confirm: delete_message}, class: "form__button form__button--delete" %>
    <% else %>
      <%= form.submit t("helpers.link.access_group.create"), class: "form__button form__button--confirm" %>
    <% end %>
  <% end %>
</div>

app/views/access_groups/index.html.erb
<div class="main-actions">
  <%= link_to t("common.back"), @map %>
</div>
<div class="container">
  <section class="section roles">
    <h2 class="section__title"><%= AccessGroup.model_name.human(count: 2) %></h2>

    <div class="role__form">
      <%= render @access_groups %>
    </div>
    <div class="role__form">
      <h3 class="subsection__title"><%= t(".new") %></h3>
      <%= render AccessGroup.new(map: @map, users: [User.new]) %>
    </div>

    <div class="role__form">
      <h3 class="subsection__title"><%= t(".new_link") %></h3>
      <%= render AccessGroup.new(map: @map, token: Devise.friendly_token.first(16)) %>
    </div>
  </section>
</div>