config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    unauthenticated do
      root "main#index"
    end

    authenticated :user do
      root "maps#index", as: :authenticated_root
    end

    resources :maps, except: [:edit] do
      resources :layers, only: [:new]
      resources :access_groups, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :layers, except: [:index, :new, :edit] do
      member do
        get :schema
        get :geojson
      end
      resources :rows, only: [:new, :create, :update, :destroy]
    end
    resources :fields, only: [:create, :update, :destroy]

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/:locale" => "main#index"
    get "share/:token", to: "access_groups#enter_by_link", as: "share_link"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/map.rb
# == Schema Information
#
# Table name: maps
#
#  id                :uuid             not null, primary key
#  default_latitude  :float
#  default_longitude :float
#  default_zoom      :float
#  name              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Map < ApplicationRecord
  # Relations
  has_many :access_groups, dependent: :destroy, inverse_of: :map
  has_many :layers, dependent: :destroy

  # Through relations
  has_many :users, through: :access_groups, inverse_of: :maps
  has_many :rows, through: :layers, inverse_of: :map

  # Query as scopes
  scope :with_last_updated_row_id, -> do
    joins(:rows)
      .order("maps.id, rows.updated_at DESC")
      .select("DISTINCT ON (maps.id) maps.*, rows.id as computed_last_updated_row_id")
  end
  belongs_to :last_updated_row, class_name: "Row", optional: true, foreign_key: "computed_last_updated_row_id" # rubocop:disable Rails/InverseOf

  # Hooks
  after_update_commit do
    if name_previously_changed?
      broadcast_i18n_replace_to self, target: dom_id(self, :name), partial: "maps/name"
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!
  before_action :new_map, only: %i[new create]
  before_action :set_map, only: %i[show update destroy]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @maps = policy_scope(Map)
  end

  def new
  end

  def create
    if @map.update(map_params)
      redirect_to new_map_layer_url(@map)
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @role_type = current_user.access_groups.find_by(map: @map)&.role_type
  end

  def update
    if @map.update(map_params)
      if [:default_latitude, :default_longitude, :default_zoom].any? { _1.in? @map.previous_changes }
        flash.now[:notice] = t("helpers.message.map.center_and_zoom_saved")
      end
      respond_to do |format|
        format.turbo_stream { render turbo_stream: [turbo_stream.update("flash", partial: "layouts/flash")] }
        format.html { redirect_to layer_path(@map) }
      end
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @map.strict_loading!(false) # deletion in cascade to layers: :fields would trigger a violation
    @map.destroy
    redirect_to maps_url, notice: t("helpers.message.map.destroyed"), status: :see_other
  end

  private

  def set_map
    @map = Map.find(params[:id])
    authorize @map
  end

  def new_map
    @map = Map.new
    @map.access_groups.new(users: [current_user], role_type: :owner)
    authorize @map
  end

  def map_params
    params.require(:map).permit(:name, :default_latitude, :default_longitude, :default_zoom)
  end
end

app/views/maps/_name.html.erb
<%# params: map %>
<%# renders a form for a map name %>

<h2 id="<%= dom_id(map, :name) %>">
  <%= form_with model: map do |form| %>
    <%= form.label :name, hidden: true %>
    <%= form.text_field :name,
          data: {
            restricted_target: "restricted",
            restricted_authorizations: %w[owner].to_json # cf MapPolicy#update?
          },
          onfocusout: "this.form.requestSubmit()",
          class: "input--restricted map__name__input" %>
  <% end %>
</h2>

app/views/maps/_toolbar.erb
<div class="map__toolbar__container">
  <div data-map-target="toolbarLeft">
  </div>
  <div>
    <button
      class="map__toolbar__add-button is-hidden"
      data-map-target="addButton"
      data-action="map#toggleMode">
    </button>
  </div>
  <div class="map__toolbar__right" data-map-target="toolbarRight">
    <div class="map__control__icon">
      <a
        download="<%= @map.name + ".png" %>"
        data-action="map#exportMapAsImage"
        title="<%= t(".export_as_image") %>"
        aria-label="<%= t(".export_as_image") %>"
      >
        <%= embedded_svg("export_as_image.svg") %>
      </a>
    </div>
    <div class="map__control__icon">
      <%= form_for @map do |f| %>
        <div class="is-hidden">
          <%= f.text_field :default_latitude, data: {map_target: "defaultLatitude"} %>
          <%= f.text_field :default_longitude, data: {map_target: "defaultLongitude"} %>
          <%= f.text_field :default_zoom, data: {map_target: "defaultZoom"} %>
        </div>
        <button
          data-action="map#setDefaultCenterZoom"
          title="<%= t(".set_center_and_zoom") %>"
          aria-label="<%= t(".set_center_and_zoom") %>"
        >
          <%= embedded_svg "map-pin.svg" %>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/maps/index.html.erb
<%# params: @maps %>
<div class="container">
  <section class="section section--small">
    <h2 class="section__title"><%= Map.model_name.human(count: 2) %></h2>
    <ul class="list">
      <% @maps.with_last_updated_row_id.includes(last_updated_row: :author).each do |map| %>
        <li class="list-element">
          <%= link_to map, class: "no-decoration list-element__link" do %>
            <div class="list-element__content">
              <h3 class="list-element__title"><%= map.name %></h3>
              <p class="list-element__description">
                <%= map.layers.size %> <%= Layer.model_name.human(count: map.layers.size) %>
                <%= updated_at_tag(map.last_updated_row, map.last_updated_row.author) %>
              </p>
            </div>
            <div class="list-element__extra"><%= embedded_svg "chevron_droite.svg" %></div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= link_to t("helpers.link.map.new"), new_map_path, class: "primary-action" %>
  </section>
</div>

app/views/maps/new.html.erb
<%# params: @map %>

<div class="centered-main new-layer modal">
  <div class="modal__container">
    <h2><%= t("helpers.link.map.new") %></h2>
    <%= form_with(model: @map, id: dom_id(@map)) do |form| %>
      <div class="form__field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
    </div>
    <div class="modal__footer">
      <%= link_to t("common.back"), maps_path, class: "secondary-action" %>
      <%= form.submit class: "form__button form__button--confirm", form: dom_id(@map) %>
    </div>
  <% end %>
</div>

app/views/maps/show.html.erb
<%# params: @map %>
<%= turbo_stream_from @map %>
<%= turbo_stream_i18n_from @map %>
<header class="main-actions">
  <%= link_to t(".all_maps"), maps_path %>
  <%= render "name", map: @map %>
  <div class="main-actions-right">
    <%= link_to t("common.share"), map_access_groups_path(@map) if policy(@map.access_groups.new).index? %>
    <%= link_to t("helpers.link.map.delete"), @map, data: {turbo_method: :delete, turbo_confirm: t("common.confirm")} if policy(@map).destroy? %>
  </div>
</header>

<% content_for :left_pane do %>
  <div
    class="map-data__container"
    data-controller="layer-selection">
    <div id="<%= dom_id(@map, "layers") %>">
      <% @map.layers.includes(:fields).order(:created_at, :id).each do |layer| %>
        <%= render layer %>
      <% end %>
    </div>
    <footer class="footer__layer-list">
      <%= link_to t("helpers.link.layer.new"), new_map_layer_path(@map), class: "primary-action" if policy(@map).update? %>
    </footer>
  </div>
<% end %>

<% content_for :right_pane do %>
  <div class="map" data-map-target="map">
    <%= render "toolbar" %>
  </div>
<% end %>

<%= render "layouts/dragbar", map: @map, role_type: @role_type, current_user_id: current_user.id %>