config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    unauthenticated do
      root "main#index"
    end

    authenticated :user do
      root "maps#index", as: :authenticated_root
    end

    resources :maps, except: [:edit] do
      resources :layers, only: [:new]
      resources :access_groups, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :layers, except: [:index, :new, :edit] do
      member do
        get :schema
        get :geojson
      end
      resources :rows, only: [:new, :create, :update, :destroy]
    end
    resources :fields, only: [:create, :update, :destroy]

    resources :territory_categories, only: [:index, :show]
    resources :territories, only: [:show] do
      collection do
        get "search"
      end
    end

    get "/:locale" => "main#index"
    get "share/:token", to: "access_groups#enter_by_link", as: "share_link"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/layer.rb
# == Schema Information
#
# Table name: layers
#
#  id            :uuid             not null, primary key
#  geometry_type :enum             geometry, 0
#  name          :string
#  style         :jsonb            not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  map_id        :uuid             not null
#
# Indexes
#
#  index_layers_on_map_id  (map_id)
#
# Foreign Keys
#
#  fk_rails_...  (map_id => maps.id)
#
class Layer < ApplicationRecord
  # Constants
  COLORS = {
    blue: "#007AFF",
    cyan: "#32ADE6",
    indigo: "#5856D6",
    purple: "#AF52DE",
    green: "#34C759",
    brown: "#A2845E",
    pink: "#FF2D55",
    orange: "#FF9500"
  }

  # Attributes
  enum :geometry_type, {point: "point", line_string: "line_string", polygon: "polygon", territory: "territory"}, prefix: "geometry"

  # Relations
  belongs_to :map
  has_many :fields, dependent: :destroy
  has_many :rows, -> { with_territory.order(:created_at) }, dependent: :delete_all, inverse_of: :layer # note: having a scope on the relation breaks statement caching and strict_loading
  has_and_belongs_to_many :territory_categories

  # Query as scopes
  scope :with_last_updated_row_id, -> do
    joins(:rows)
      .order("layers.id, rows.updated_at DESC")
      .select("DISTINCT ON (layers.id) layers.*, rows.id as computed_last_updated_row_id")
  end
  belongs_to :last_updated_row, class_name: "Row", optional: true, foreign_key: "computed_last_updated_row_id" # rubocop:disable Rails/InverseOf

  # Hooks
  after_create_commit -> { broadcast_i18n_append_to map, target: dom_id(map, "layers") }
  after_update_commit -> { broadcast_i18n_replace_to map }
  after_destroy_commit -> { broadcast_remove_to map }

  def geo_feature_collection
    RGeo::GeoJSON::FeatureCollection.new(rows.map(&:geo_feature))
  end

  def color
    style["color"] || COLORS[:blue]
  end

  def color=(new_color)
    style["color"] = new_color
  end

  # Dynamic Fields Associations
  # return all the names for the dynamic associations.
  # They can be used in `.includes` or `.preload`/`.eager_load` for the rows of this layer.
  def fields_association_names
    fields.type_territory.map(&:association_name)
  end
end

app/controllers/layers_controller.rb
require "securerandom"

class LayersController < ApplicationController
  before_action :access_by_apikey, only: %i[geojson]
  before_action :authenticate_user!
  before_action :set_layer, only: %i[show update destroy schema geojson]

  def new
    map = current_user.maps.find(params["map_id"])
    @layer = authorize map.layers.new
  end

  def create
    map = current_user.maps.find(layer_params["map_id"])

    layer = authorize map.layers.new(layer_params)
    if layer.save
      redirect_to layer.map
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new", status: :unprocessable_entity
    end
  end

  def show
    redirect_to @layer.map
  end

  def update
    if @layer.update(layer_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to layer_path(@layer) }
      end
    else
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @layer.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @layer.map, notice: t("helpers.message.layer.destroyed"), status: :see_other }
    end
  end

  def schema
    properties = @layer.fields.all.map { |f| field_schema(f) }.to_h

    render json: {
      type: :object,
      properties: properties
    }.to_json
  end

  def geojson
    send_data RGeo::GeoJSON.encode(@layer.geo_feature_collection).to_json, filename: "#{@layer.name}.geojson", type: "application/geo+json"
  end

  private

  def set_layer
    @layer = authorize Layer.includes(:map, rows: :territory, fields: :territory_categories).find(params[:id])
  end

  def layer_params
    params.require(:layer).permit(:name, :geometry_type, :map_id, :color, territory_category_ids: [])
  end

  def field_schema(field)
    mapping = {
      "text" => :string,
      "float" => :number,
      "integer" => :integer
    }

    [field.id, type: mapping[field.field_type], title: field.label]
  end

  def access_by_apikey
    token = params["authkey"] || request.headers["X-Auth-Key"]
    if token.present? && !user_signed_in?
      access_group = AccessGroup.find_by(token: token)
      if access_group.present?
        headers["Access-Control-Allow-Origin"] = "*"
        headers["Access-Control-Allow-Methods"] = "GET OPTIONS"
        headers["Access-Control-Allow-Headers"] = "*"
        sign_in User.new(access_groups: [access_group], remember_me: false)
      else
        render plain: t("api.bad_key"), status: :unauthorized
      end
    end
  end
end

app/views/layers/_layer.html.erb
<div
  id="<%= dom_id(layer) %>"
  class="layer-container"
  data-controller="layer"
  data-layer-selection-target="layer"
  data-action="layer:center->map#fitBounds layer:opened->layer-selection#opened">
  <header class="layer-header">
    <div class="layer-header__left-description">
      <%= embedded_svg "#{layer.geometry_type}.svg", class: "layer-header__icon", style: "color: #{layer.color}" %>
      <%= render "layers/name", layer: layer %>
    </div>
    <div class="layer-header__right-tools">
      <span class="layer-header__action"
        title="<%= t(".center_on_layer") %>"
        data-action="click->layer#center">
        <%= embedded_svg "frame.svg" %>
      </span>
      <button
        class="layer-header__chevron chevron"
        data-action="layer#toggleTable map#layerToggle"
        data-map-layer-id-param="<%= layer.id %>"
        data-map-add-feature-text-param="<%= t("common.add_geometry.#{layer.geometry_type}") %>"
        data-map-geometry-type-param="<%= layer.geometry_type %>">
      </button>
    </div>
  </header>

  <div class="layer-table__body" data-layer-switch-target="content">
    <%= render "layers/rows", layer: layer %>

    <footer class="layer-footer">
      <div data-restricted-target="restricted" data-restricted-authorizations="<%= %w[owner editor contributor].to_json %>"> <%# Cf policy(layer).edit? %>
        <%= link_to t("helpers.link.layer.add_point"), new_layer_row_path(layer) if layer.geometry_point? %>
      </div>
      <div class="layer-footer__icon">
        <%= link_to layer, data: {turbo_method: :delete, turbo_confirm: t("common.confirm")}, title: t("helpers.link.layer.delete") do %>
          <%= embedded_svg "delete.svg" %>
        <% end %>
      </div>
      <div class="layer-footer__icon">
        <%= link_to geojson_layer_path(layer), download: "#{layer.name}.geojson", title: t("helpers.link.layer.geojson_export") do %>
          <%= embedded_svg "export.svg" %>
        <% end %>
      </div>
    </footer>
  </div>
</div>

app/views/layers/_name.html.erb
<%# params: layer %>
<%# renders a form for a layer name %>

<h3>
  <%= form_with model: layer do |form| %>
    <%= form.label :name, hidden: true %>
    <%= form.text_field :name,
          data: {
            restricted_target: "restricted",
            restricted_authorizations: %w[owner editor].to_json # cf LayerPolicy#update?
          },
          onfocusout: "this.form.requestSubmit()",
          class: "input--restricted map__toolbar__input" %>
  <% end %>
</h3>

app/views/layers/_rows.html.erb
<%# params: layer %>
<%# renders a full table of editable rows for a layer %>

<table class="layer-table">
  <thead class="resizable">
    <tr>
      <% if layer.geometry_territory? %>
        <th><span class="layer-table__header"></span></th>
        <th><span class="layer-table__header"><%= t("common.territory_code") %></span></th>
      <% elsif layer.geometry_point? %>
        <th><span class="layer-table__header"><%= t("common.longitude") %></span></th>
        <th><span class="layer-table__header"><%= t("common.latitude") %></span></th>
      <% elsif layer.geometry_line_string? %>
        <th><span class="layer-table__header"><%= t("common.length") %></span></th>
      <% elsif layer.geometry_polygon? %>
        <th><span class="layer-table__header"><%= t("common.area") %></span></th>
      <% end %>

      <%= render layer.fields %>

      <%= render Field.new(layer: layer) %>
    </tr>
  </thead>
  <tbody id="<%= dom_id(layer, "rows") %>">
  <%= render layer.rows.includes(:territory, *layer.fields_association_names) %>
  </tbody>
</table>

<%= render "rows/new", row: Row.new(layer: layer) %>

app/views/layers/new.html.erb
<%# params: @layer %>

<div
  class="centered-main new-layer modal"
  data-controller="new-layer"
  data-new-layer-default-color-value="<%= Layer::COLORS[:blue] %>">
  <div class="modal__container">
    <h2><%= t("helpers.link.layer.new") %></h2>
    <%= form_with(model: @layer, id: dom_id(@layer)) do |form| %>
      <%= form.hidden_field :map_id %>

      <div class="form_field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <h3><%= Layer.human_attribute_name(:color) %></h3>
      <div class="color-selection__container">
        <% Layer::COLORS.each do |key, rgb| %>
          <div class="color-selection__option">
            <%= form.radio_button :color, rgb, checked: key == :blue, data: {"new-layer-color-param": rgb, action: "new-layer#colorSelected"} %>
            <%= form.label :color, t(key, scope: "colors"), value: rgb %>
          </div>
        <% end %>
      </div>

      <h3><%= Layer.human_attribute_name(:geometry_type) %></h3>
      <div class="geometry-type-selector">
        <% Layer.geometry_types.keys.each do |type| %>
          <%= form.label "geometry_type_#{type}" do %>
            <%= form.radio_button :geometry_type, type, checked: type == "point", data: {"new-layer-type-param": type, action: "new-layer#typeSelected"} %>
            <div>
              <div data-new-layer-target="icon"><%= embedded_svg "#{type}.svg" %></div>
              <%= Layer.human_attribute_name(type).capitalize %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="territory-categories is-hidden" data-new-layer-target="territoryCategories">
        <h3><%= TerritoryCategory.model_name.human(count: 2) %></h3>
        <%= form.collection_check_boxes :territory_category_ids, TerritoryCategory.all, :id, :to_s do |b| %>
          <div><%= b.label { b.check_box + b.text } %></div>
        <% end %>
      </div>
    </div>

    <div class="modal__footer">
      <%= link_to t("common.back"), map_path(@layer.map), class: "secondary-action" %>
      <%= form.submit class: "form__button form__button--confirm", form: dom_id(@layer) %>
    </div>
  <% end %>

</div>